"""empty message

Revision ID: cdcab635ed89
Revises: e3482517fc52
Create Date: 2021-02-06 19:13:46.390823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdcab635ed89'
down_revision = 'e3482517fc52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('portrait', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'portrait')
    # ### end Alembic commands ###
